export const shoppinglistCategories = {
  "Frugt & grønt": "🍏🥕",
  "Brød & bageri": "🥖🍞",
  "Kød & fisk": "🍗🐟",
  "Mejeri & æg": "🥛🥚",
  Frostvarer: "❄️🍕",
  "Kolonial (tørvarer, konserves, pasta, ris, osv.)": "🍚🥫",
  "Snacks & slik": "🍫🍿",
  "Drikkevarer (sodavand, juice, kaffe, te, osv.)": "☕🥤",
  "Vin & spiritus": "🍷🍾",
  Rengøringsmidler: "🧼🧹",
  "Papirvarer (toiletpapir, køkkenrulle osv.)": "🧻",
  "Dyrefoder (til hund, kat, fugle osv.)": "🐶🐱",
  andet: "??",
} as const;
