import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/smallComponent/Navbar";
import { RecipeProvider } from "./context/RecipeContext";
import { ShoppingListProvider } from "./context/ShoppinglistContext";
import { SessionProviderWrapper } from "./components/authentication/SessionProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProviderWrapper>
          <RecipeProvider>
            <ShoppingListProvider>
              <NavBar></NavBar>
              <main>{children}</main> {/* Wrap content in a <main> */}
            </ShoppingListProvider>
          </RecipeProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
